// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hewcaikalseorcmmjark.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhld2NhaWthbHNlb3JjbW1qYXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjM0NzIsImV4cCI6MjA3MDI5OTQ3Mn0.N5Y8Cw9D0uml9CGYK78a3WZCt-HL9jRt0DoCyBcJ20Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
    storageKey: 'padu-auth-token'
  }
});